In [1]:
pip install torch torchvision

     |████████████████████████████████| 97.5 MB 20.9 MB/s eta 0:00:01
     |████████████████████████████████| 387 kB 13.2 MB/s eta 0:00:01
     |████████████████████████████████| 829 kB 17.4 MB/s eta 0:00:01
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=5ab05427fe8093e4e24704c9c14cc70c6a40073bfe94bbd934a3961f57847931
  Stored in directory: /Users/hwangjeahong/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built future
Note: you may need to restart the kernel to use updated packages.


In [2]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.2117, 0.2679, 0.6813],
        [0.4061, 0.2753, 0.0444],
        [0.4306, 0.8344, 0.4668],
        [0.6962, 0.9548, 0.6357],
        [0.5529, 0.5767, 0.1538]])


In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd
import numpy as np

In [4]:
torch.manual_seed(1)

In [5]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [6]:
W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [7]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W)+b)))

In [8]:
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [9]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

In [10]:
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)


In [18]:
output_set = pd.read_csv("fraction3.csv",encoding="CP949")
input_set = pd.read_csv("data_regular.csv", encoding="UTF-8")

In [19]:
datas = []
data = []
for i in range(0,424):
    data.clear()
    a = input_set.loc[i].values
    b = a[4:]
    for item in b:
        data.append(item)
    datas.append(data)
    

In [20]:
x_train = torch.FloatTensor(datas)

In [21]:
x_train.shape

torch.Size([424, 15])

In [23]:
twenty_o = output_set["20~29세"]

In [26]:
twenty_o = twenty_o.values

In [28]:
twenty = []
for item in twenty_o:
    twenty.append(item)

In [29]:
y20_train = torch.FloatTensor(twenty)

In [40]:
def sigmoid(Z):
    return 1/(1+e^-Z)
def relu(x):
    return(0,x)

In [41]:
def initialize_parameters(layer_dim):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dim)
    
    for l in range(1,L):
        parameters['W'+str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1])
        parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))
    return parameters

In [42]:
def linear_forward(A,W,b):
    z = np.dot(W,A) + b
    
    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache

In [46]:
def linear_activation_forward(A_prev, W, b, activation):
    if activation == "sigmoid":
        Z, linear_cache = linear_forward(A_prev,W,b)
        A, activation_cache = sigmoid(Z)
    elif activation == 'relu':
        Z, linear_cache = linear_forward(A_prev, W,b)
        A, activation_cache = relu(Z)
    assert (A.shpae == (W.shape[0], A_prev.shpae[1]))
    cache = (linear_cache, activation_cache)
    
    return A, cache

In [47]:
def multi_layer_forward(X, parameters):
    cache = []
    A = X
    L = len(parameters)
    
    for l in range(1,L):
        A_prev = A
        A, cache = linear_activation_forward(A_prev, parameters['W' + str(l)], parameters['b'+str(l)], activation = 'relu')
        caches.append(cache)
        
        AL, cache = linear_activation_forward(A, parameters['W' + str(L)], parameters['b'+str(L)], activation = 'sigmoid')
        caches.append(cache)
        
        assert(AL.shape == (1,X.shape[1]))
        
        return AL, caches

In [48]:
def compute_cost(AL, Y):
    m = Y.shpae[1]
    
    cost = (-1/m) * np.sum((np.multiply(Y,np.log(AL)) + np.multiply(1-Y, np.log(1-AL))))
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    return cost

In [49]:
def linear_backward(dZ, cache):
    A_prev, W, b = cache
    m = A_prev.shape[1]
    dW = 1/m*np.dot(dZ, A_prev.T)
    db = 1/m*np.sum(dZ, axis=1, keepdims = True)
    dA_prev = np.dot(W.T, dZ)
    
    assert(dA_prev.shape == A_prev.shape)
    assert(dW.shape == W.shape)
    assert(db.shape == b.shape)
    
    return dA_prev, dW, db

In [50]:
def linear_activation_backward(dA, cache, activation):
    linear_cache, activation_cache = cache
    if activation == 'relu':
        dZ = relu_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
        
    elif activation == "sigmoid":
        dZ = sigmoid_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)

In [54]:
def multi_layer_backward(AL, Y, caches):
    grads = {}
    L = len(caches)
    m = AL.shape[1]
    Y = Y.reshape(AL.shape)
    
    dAL = -(np.divide(Y,AL) - np.divide(1-Y, 1-AL))
    
    current_cache = caches[L-1]
    grads["dA" + str(L-1)], grads["dW" + str(L)], grads["db" + str(L)] = linear_activation_backward(dAL, current_cache, activation="sigmoid")
    
    for l in reversed(range(L-1)):
        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = linear_activation_backward(grads["dA" + str(l+1)], current_cache, activation="relu")
        grads["dA" + str(l)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] = db_temp
    return grads

In [55]:
def update_parameters(parameters, grads, learning_rate):
    L = len(parameters)
    
    for l in range(L):
        parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate*grads["dW" + str(l+1)]
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate*grads["db" + str(l+1)]
        
    return parameters