In [3]:
pip install torch torchvision

     |████████████████████████████████| 97.4MB 197kB/s  eta 0:00:01     |███████████████▏                | 46.2MB 31.2MB/s eta 0:00:02     |████████████████████▎           | 61.7MB 35.8MB/s eta 0:00:01     |██████████████████████████▉     | 81.5MB 35.8MB/s eta 0:00:01     |███████████████████████████▋    | 84.2MB 10.7MB/s eta 0:00:02     |█████████████████████████████   | 88.3MB 10.7MB/s eta 0:00:01
     |████████████████████████████████| 389kB 35.0MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [16]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635]])


In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd

In [7]:
torch.manual_seed(1)

In [8]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [11]:
W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [12]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W)+b)))

In [13]:
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [14]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

In [15]:
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)


In [164]:
output_set = pd.read_csv("fraction3.csv",encoding="CP949")
input_set = pd.read_csv("data_regular.csv", encoding="UTF-8")

In [108]:
datas = []
data = []

In [159]:
datas = []
data = []
for i in range(0,424):
    data.clear()
    a = input_set.loc[i].values
    b = a[4:]
    for item in b:
        data.append(item)
    datas.append(data)
    

In [161]:
x_train = torch.FloatTensor(datas)

In [165]:
x_train.shape

torch.Size([424, 15])

Unnamed: 0     동      0~4세      5~9세    10~14세    15~19세    20~24세  \
0             1   사직동  0.081948  0.100258  0.092634  0.081941  0.076412   
1             2   삼청동  0.019463  0.022340  0.032569  0.026396  0.023410   
2             3   부암동  0.076826  0.098896  0.117994  0.114534  0.108214   
3             4   평창동  0.170725  0.192887  0.191407  0.217592  0.178737   
4             5   무악동  0.100387  0.118784  0.129207  0.124174  0.070965   
..          ...   ...       ...       ...       ...       ...       ...   
419         420  둔촌1동  0.000000  0.001635  0.001335  0.000918  0.001472   
420         421  둔촌2동  0.290916  0.289876  0.265888  0.307567  0.260450   
421         422  암사1동  0.365694  0.337280  0.328355  0.354161  0.323759   
422         423  천호2동  0.346231  0.246830  0.226645  0.254546  0.276056   
423         424    길동  0.424765  0.389861  0.364928  0.411772  0.426378   

       25~29세    30~34세    35~39세  ...    55~59세    60~64세    65~69세  \
0    0.089001  0.096661  0.096456  ...  0.100094  0.099644  0.093722   
1    0.022367  0.025451  0.029455  ...  0.030424  0.035667  0.036716   
2    0.092632  0.090463  0.085963  ...  0.105974  0.107138  0.099519   
3    0.153293  0.139123  0.155746  ...  0.212332  0.201786  0.195367   
4    0.054689  0.055253  0.071426  ...  0.087566  0.078272  0.082321   
..        ...       ...       ...  ...       ...       ...       ...   
419  0.001405  0.000527  0.002781  ...  0.002173  0.003747  0.005411   
420  0.250375  0.263476  0.262315  ...  0.301560  0.318917  0.313051   
421  0.324035  0.340224  0.382411  ...  0.398586  0.397189  0.405420   
422  0.376382  0.429895  0.403143  ...  0.414438  0.409263  0.400396   
423  0.502740  0.512841  0.484556  ...  0.510057  0.558729  0.552670   

       70~74세    75~79세    80~84세    85~89세    90~94세    95~99세  100세 이상+  
0    0.099853  0.127221  0.161011  0.190478  0.219291  0.220192  0.289811  
1    0.041752  0.044064  0.053128  0.067778  0.071038  0.077067  0.122026  
2    0.114693  0.116951  0.142037  0.149578  0.169874  0.242211  0.167785  
3    0.189394  0.218661  0.258052  0.328371  0.352102  0.462402  0.381330  
4    0.090044  0.097404  0.113846  0.107509  0.117367  0.121105  0.259304  
..        ...       ...       ...       ...       ...       ...       ...  
419  0.006791  0.004307  0.003795  0.005843  0.015443  0.033029  0.122026  
420  0.270384  0.220318  0.213598  0.268773  0.293418  0.220192  0.183038  
421  0.395138  0.355821  0.333407  0.320191  0.352102  0.286249  0.366077  
422  0.394886  0.387626  0.348045  0.286302  0.352102  0.418364  0.366077  
423  0.502285  0.431359  0.378404  0.445229  0.432406  0.484421  0.350824  

[424 rows x 23 columns]

[[1, 2], [1, 3]]